name: Playwright Tests

on:
  push:
    branches:
      - main
      - developer
  pull_request:
    branches:
      - main
      - developer

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      # Клонирование репозитория
      - uses: actions/checkout@v4

      # Установка Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Установка зависимостей проекта
      - name: Install dependencies
        run: npm ci

      # Установка браузеров Playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Запуск тестов Playwright
      - name: Run Playwright tests
        run: npx playwright test

      # Загрузка отчета о тестировании как артефакт
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30